spring:
  application:
    name:
      taco-cloud-admin
  security:
    oauth2:
      client:
        provider:
          tacocloud:
            issuer-uri: http://authserver:9000
#            authorization-uri: http://authserver:9000/oauth2/authorize
#            token-uri: http://authserver:9000/oauth2/token
#            jwk-set-uri: http://authserver:9000/oauth2/jwks
#            user-info-uri: http://authserver:9000/userinfo
#            user-name-attribute: sub
        registration:
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization-code
            redirect-uri: "http://localhost:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
logging:
  level:
    sql: debug
    web: debug
    org:
      springframework:
        security: debug
server:
  port: 9090

